config/routes.rb
Documentaries::Application.routes.draw do
  root("welcome#index")

  devise_for("users")

  resources("reviews")
  resources("search")
  resources("documentaries")
  resources("users")
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can(:read, :all)

    unless user
      can(:create, [User, :session])
    else
      if user.role?("regular")
        can(:create, [Documentary, Review])

        can([:destroy, :update], Documentary, uploader: user)
        can([:destroy, :update], Review, reviewer: user)
        can(:update, User, id: user.id)
        can(:destroy, :session)
      end

      if user.role?("admin")
        can(:manage, :all)
        can(:assign_roles)
      end
    end
  end
end

app/models/documentary.rb
class Documentary < ActiveRecord::Base
  attr_reader(:select_list)

  belongs_to(:uploader, class_name: "User")
  has_many(:reviews, foreign_key: "documentary_id")

  validates_presence_of(:title)
  validates_presence_of(:description)
  validates_presence_of(:video_source)
  validates_presence_of(:video_service)
  validates_presence_of(:tag_list)

  validates_uniqueness_of(:title)
  validates_uniqueness_of(:video_source)

  after_initialize(:create_arrays)

  before_save(:defaults)
  before_save(:create_thumbnail)

  acts_as_taggable_on(:tags)

  # will_paginate setting
  self.per_page = 8

  def create_arrays
    @select_list = ["youtube"]
  end

  def defaults
    self.likes ||= 0
    self.dislikes ||= 0
    self.total_rating ||= 0;
  end

  def create_thumbnail
    self.thumbnail_url = "https://img.youtube.com/vi/#{video_source}/mqdefault.jpg"
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to(:documentary)
  belongs_to(:reviewer, class_name: "User")

  validates_presence_of(:message)
  validates_presence_of(:documentary_id)
end

app/models/user.rb
class User < ActiveRecord::Base
  devise(
    :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  )

  attr_accessor(:login)

  ROLES = %w[regular admin]

  validates_presence_of(:name)
  validates_uniqueness_of(:name)
  validates_presence_of(:email)
  validates_uniqueness_of(:email)

  before_save(:default_values)

  has_many(:documentaries, foreign_key: "uploader_id")
  has_many(:reviews, foreign_key: "reviewer_id")

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value OR email = :value", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  def default_values
    self.role ||= "regular"
  end

  def role?(base_role)
    ROLES.index(base_role.to_s) <= ROLES.index(role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery(:with => :exception)

  before_action(:configure_permitted_parameters, :if => :devise_controller?)

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :password, :remember_me) }
  end
end

app/controllers/documentaries_controller.rb
class DocumentariesController < ApplicationController
  load_and_authorize_resource
  
  def show
    @documentary = Documentary.find(params[:id])
    @review = @documentary.reviews.where(reviewer: current_user).first || Review.new
    @reviews = @documentary.reviews.order("updated_at asc")
  end

  def new
    @documentary = Documentary.new
  end

  def create
    @documentary = Documentary.new(documentary_params)
    @documentary.uploader = current_user

    if @documentary.save
      redirect_to(documentary_path(@documentary), notice: "Documentary created")
    else
      flash.now.alert = "Error"
      render(:new)
    end
  end

  def edit
    @documentary = Documentary.find(params[:id])
  end

  def update
    @documentary = Documentary.find(params[:id])

    if @documentary.update(documentary_params)
      redirect_to(documentary_path(@documentary))
    else
      render(:edit)
    end
  end

  def destroy
    @documentary = Documentary.find(params[:id])

    if @documentary.destroy
      redirect_to(root_path, notice: "Destroyed Documentary")
    else
      render(:edit)
    end
  end
end

private
  def documentary_params
    params.require(:documentary).permit(
      :title, :description, :video_source, :video_service, :tag_list
    )
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource

  def create
    review = Review.new(review_params)
    review.reviewer = current_user

    if params[:review][:is_positive] == "true"
      review.documentary.likes += 1
      review.documentary.total_rating += 1
    else
      review.documentary.dislikes += 1
      review.documentary.total_rating -= 1
    end

    review.save
    review.documentary.save

    redirect_to(:back)
  end

  def update
    review = Review.where(documentary_id: params[:review][:documentary_id], reviewer_id: current_user.id).first

    if params[:review][:is_positive] != review.is_positive.to_s
      if params[:review][:is_positive] == "true"
        review.documentary.likes += 1
        review.documentary.dislikes -= 1
        review.documentary.total_rating += 2
      else
        review.documentary.likes -= 1
        review.documentary.dislikes += 1
        review.documentary.total_rating -= 2
      end
    end

    review.update(review_params)
    review.documentary.save

    redirect_to(:back)
  end

private
  def review_params
    params.require(:review).permit(:message, :is_positive, :documentary_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  authorize_resource(:class => false)
  
  def index
    @documentaries = Documentary
      .tagged_with(params[:search])
      .order("created_at DESC")
      .paginate(:page => params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  def show
    @user = User.find(params[:id])
    @documentaries = @user.documentaries.order("created_at desc").paginate(page: params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    # Allow user to leave password unchanged
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    if @user.update(user_params)
      redirect_to(user_path(@user))
    else
      render(:edit)
    end
  end

private
  def user_params
    allowed_params = [:name, :email, :password, :current_password]
    allowed_params << :role if can?(:assign_roles, current_user)
    params.require(:user).permit(allowed_params)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  authorize_resource(:class => false)
  
  def index
    @best_documentaries = Documentary.order("total_rating DESC").limit(4)
    @random_documentaries = Documentary.order("RANDOM()").limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include FoundationRailsHelper::FlashHelper
end

app/views/documentaries/_form.html.haml
= f.text_field(:title, placeholder: "Test Title")
= f.text_area(:description, placeholder: "Test Description")
= f.text_field(:tag_list, placeholder: "Tag One, Tag Two")
= f.select(:video_service, @documentary.select_list)
= f.text_field(:video_source, placeholder: "M7lc1UVf-VE")
  

app/views/documentaries/edit.html.haml
= form_for(@documentary, method: :patch) do |f|
  = link_to("Destroy", documentary_path(@documentary), method: :delete, |
    class: "small button alert") if can?(:destroy, @documentary)        |
  = render(partial: "form", locals: {f: f})
  = f.submit("Save Changes")

app/views/documentaries/new.html.haml
= form_for(@documentary) do |f|
  = render(partial: "form", locals: {f: f})
  = f.submit("Upload!")

app/views/documentaries/show.html.haml
%div
  %h1= @documentary.title
  %p= @documentary.description
  - if @documentary.video_service == "youtube"
    #video-player.video-wrapper
      %iframe#ytplayer{:allowfullscreen => "", :frameborder => "0", :src => "//www.youtube.com/embed/#{@documentary.video_source}", :type => "text/html"}
  %h3
    Uploaded by #{link_to(@documentary.uploader.name, user_path(@documentary.uploader))}
  %span
    = @documentary.likes
    likes, and
  %span
    = @documentary.dislikes
    dislikes
  %p
    Tags: #{raw @documentary.tag_list.map { |tag| link_to(tag, search_index_path(search: tag)) }.join(", ")}
  = link_to("Edit Documentary", edit_documentary_path(@documentary), class: "small button") if can?(:edit, @documentary)
- if @review.new_record?
  = form_for(@review, url: reviews_path) do |f|
    = f.hidden_field("documentary_id", value: @documentary.id)
    = f.text_area(:message, label: "Review", placeholder: "Test Message")
    .form-group
      .radio.col-sm-offset-2
        %label
          %input{:checked => "", :name => "review[is_positive]", :type => "radio", :value => "true"}/
          Liked
      .radio.col-sm-offset-2
        %label
          %input{:name => "review[is_positive]", :type => "radio", :value => "false"}/
          Disliked
      = f.submit("Submit Review")
- elsif current_user
  = form_for(@review, url: review_path(@review), method: :patch) do |f|
    = f.hidden_field("documentary_id", value: @documentary.id)
    = f.text_area(:message, label: "Review", placeholder: "Test Message", value: @review.message)
    %label
      <input type="radio" name="review[is_positive]" value="true" #{"checked" if @review.is_positive}>
      Liked
    %label
      <input type="radio" name="review[is_positive]" value="false" #{"checked" unless @review.is_positive}>
      Disliked
    = f.submit("Update Review")
- @reviews.each do |review|
  %hr/
  %p= review.message
  %p= review.is_positive ? "Liked" : "Disliked"
  %p
    Posted by #{link_to(review.reviewer.name, user_path(review.reviewer))}

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title Documentaries
    = stylesheet_link_tag("application", media: "all", "data-turbolinks-track" => true)
    = csrf_meta_tags
  %body
    .contain-to-grid
      %nav#navbar.top-bar{"data-topbar" => ""}
        %ul.title-area
          %li.name
            %h1= link_to("Documentaries", root_path)
          %li.toggle-topbar.menu-icon
            %a{:href => "#"}
              %span Menu
        %section.top-bar-section
          %ul.right
            / Search form
            %li.has-form
              %form{:action => search_index_path, :method => "get"}
                .row.collapse
                  .large-8.small-9.columns
                    = text_field_tag("search", params[:search], placeholder: "Tag One, Tag Two")
                  .large-4.small-3.columns
                    = submit_tag("Search", name: nil, class: "alert button expand")
            - if user_signed_in?
              %li= link_to("Upload", new_documentary_path)
              %li= link_to("Profile", user_path(current_user))
              %li= link_to("Sign Out", destroy_user_session_path, :method => :delete)
            - else
              %li= link_to("Sign Up", new_user_registration_path)
              %li= link_to("Sign In", new_user_session_path)
    .row
      .columns
        = display_flash_messages
        = yield
    = javascript_include_tag("vendor/modernizr")
    = javascript_include_tag("application")

app/views/search/index.html.haml
%div
  %h2 Documentaries:
  %hr/
  - @documentaries.each do |documentary|
    .small-6.medium-3.columns.end{"data-id" => documentary.id}
      = link_to(documentary_path(documentary)) do
        %img{:height => "127", :src => documentary.thumbnail_url, :width => "225"}/
        %h3= documentary.title
      %span
        = documentary.likes
        likes, and
      %span
        = documentary.dislikes
        dislikes
%div
  .large-12.columns
    = will_paginate(@documentaries, renderer: FoundationPagination::Rails)

app/views/users/_form.html.haml
= f.text_field(:name, label: "Username", placeholder: "Username")
= f.email_field(:email, label: "Email Address", placeholder: "Email Address")
= f.password_field(:password, placeholder: "Password")
= f.collection_select(:role, User::ROLES, :to_s, :humanize) if can?(:assign_roles, current_user)

app/views/users/edit.html.haml
= form_for(@user, url: user_path, method: :patch) do |f|
  = render(partial: "form", locals: {f: f})
  = f.submit("Save Changes")

app/views/users/show.html.haml
#user-info
  %h1= @user.name
  = link_to("Edit Profile", edit_user_path, class: "small button") if can?(:edit, @user)
#user-documentaries
  %h2.title-divider Uploaded Documentaries
  .row
    - @documentaries.each do |documentary|
      .small-6.medium-3.columns.end.documentary-container{"data-id" => documentary.id}
        = link_to(documentary_path(documentary), title: documentary.title) do
          %img{:height => "127", :src => documentary.thumbnail_url, :width => "225"}/
          %h3= documentary.title
        %span
          = documentary.likes
          likes, and
        %span
          = documentary.dislikes
          dislikes
= will_paginate(@documentaries, renderer: FoundationPagination::Rails)

app/views/welcome/index.html.haml
.best-documentaries
  %h2.title-divider Best:
  .row
    - @best_documentaries.each do |documentary|
      .small-6.medium-3.columns.end.documentary-container{"data-id" => documentary.id}
        = link_to(documentary_path(documentary), title: documentary.title) do
          %img{:height => "127", :src => documentary.thumbnail_url, :width => "225"}/
          %h3= documentary.title
        %span
          = documentary.likes
          likes, and
        %span
          = documentary.dislikes
          dislikes
.random-documentaries
  %h2.title-divider Random:
  .row
    - @random_documentaries.each do |documentary|
      .small-6.medium-3.columns.end.documentary-container{"data-id" => documentary.id}
        = link_to(documentary_path(documentary), title: documentary.title) do
          %img{:height => "127", :src => documentary.thumbnail_url, :width => "225"}/
          %h3= documentary.title
        %span
          = documentary.likes
          likes, and
        %span
          = documentary.dislikes
          dislikes